# Copyright (C) 2024 Mitsubishi Electric Research Laboratories (MERL)
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: LIP4RID
channels:
  - defaults
  - conda-forge
dependencies:
  - nomkl
  - python=3.8
  - numpy
  - matplotlib
  - dill==0.3.8
  - ipython
  - black
  - pre_commit
  - flake8
  - pytest
  - pickleshare
  - pandas < 2.0.0
  - scipy
  - jax
